# .readthedocs.yml

version: 2
name: ShopEase EDA Docs
repo_url: https://github.com/Sherwin-14/shopease_analysis
format: mkdocs
mkdocs_config_file: mkdocs.yml
build_dir: eda_findings
theme: mkdocs-material
language: en
copyright: 2024 Sherwin Varghese
