site_name: EDA Docs For Ecommerce Analysis
site_url: https://mydomain.org/ecommerce
nav:
  - Home: home.md
  - Categories and Items: Categories_and_Items.md
  - Prices and Brands: Prices_and_Brands.md
  - Time Distribution Analysis: Time_Distribution_Analysis.md
  - Brand Analysis Extended: brand_analysis_extended.md
  - Requested Items Analysis : requested_analysis_extended.md
  - Customer Segmentation Model: Customer_Segmentation_model.md
theme:
  name: material
  features:
    - content.code.select

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  
    